module.exports = [{
        url: '/',
        fn: require('../controller/main'),
        method: 'get'
    }, {
        url: '/submit',
        fn: require('../controller/submit'),
        method: 'post'
    }, {
        url: '/delete',
        fn: require('../controller/delete'),
        method: 'post'
    }, {
        url: '/login',
        fn: require('../controller/login'),
        method: 'post'
    }, {
        url: '/logout',
        fn: require('../controller/logout'),
        method: 'post'
    }, {
        url: '/register_page',
        fn: require('../controller/register_page'),
        method: 'get'
    }, {
        url: '/register_user',
        fn: require('../controller/register_user'),
        method: 'post'
    }, {
        url: /^\/markdown/,
        fn: require('../controller/markdown'),
        method: 'get'
    }, {
        url: '/get_article',
        fn: require('../controller/get_article'),
        method: 'post'
    }, {
        url: '/publish_page',
        fn: require('../controller/publish_page'),
        method: 'get'
    }, {
        url: '/publish_article',
        fn: require('../controller/publish_article'),
        method: 'post'
    }, {
        url: '/getInitData',
        fn: require('../controller/web/getInitData'),
        method: 'post'
    }
]